version: 2
updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "hamisionesmus"
    assignees:
      - "hamisionesmus"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "hamisionesmus"
    assignees:
      - "hamisionesmus"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "hamisionesmus"
    assignees:
      - "hamisionesmus"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "hamisionesmus"
    assignees:
      - "hamisionesmus"